// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "LipiLab",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "LipiLab",
            targets: ["AppModule"],
            bundleIdentifier: "omkar.pujeri-mitwpu.edu.in.LipiLab",
            teamIdentifier: "MF55D5LA8H",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cloud),
            accentColor: .presetColor(.red),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            exclude: ["Assets.xcassets"] // This fixes the duplicate assets warning
        )
    ],
    swiftLanguageModes: [.v6] // This fixes the deprecated language warning
)
